# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 474bfbde6e0332737d9feff04ca794465b1b57f40707dfa8f6fc501932bc372cebe34c168856ae0fada213cf04f64f610d5bad1f7ee23d9d7781c9649a3669a2

test:
  secret_key_base: f49a2c1ab33e42bb604e866206051fbdaf0a7024914a6f05c8aa8f34937a0dc5e0695d48e526803ea617a4a085ef2d56f3424fa54fb930fadfee9262f09cf95a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
